// Generated by CoffeeScript 1.6.3
(function() {
  var DaylightPlugin;

  module.exports = function(game, opts) {
    return new DaylightPlugin(game, opts);
  };

  DaylightPlugin = (function() {
    function DaylightPlugin(game, opts) {
      this.game = game;
      if (opts == null) {
        opts = {};
      }
      if (opts.ambientColor == null) {
        opts.ambientColor = 0x888888;
      }
      if (opts.directionalColor == null) {
        opts.directionalColor = 0xffffff;
      }
      this.ambientLight = new game.THREE.AmbientLight(opts.ambientColor);
      this.directionalLight = new game.THREE.DirectionalLight(opts.directionalColor, 1);
      this.directionalLight.position.set(1, 1, 0.5).normalize();
      this.enable();
    }

    DaylightPlugin.prototype.enable = function() {
      this.game.scene.add(this.ambientLight);
      return this.game.scene.add(this.directionalLight);
    };

    DaylightPlugin.prototype.disable = function() {
      this.game.scene.remove(this.ambientLight);
      return this.game.scene.remove(this.directionalLight);
    };

    return DaylightPlugin;

  })();

}).call(this);
